<?php
namespace KeenVantage\FacebookAuthentication\Controller;

use TYPO3\Flow\Security\Authentication\Controller\AbstractAuthenticationController;

class TokenController extends AbstractAuthenticationController
{

    /**
     * @return string
     */
    public function authenticateAction()
    {
        return parent::authenticateAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \TYPO3\Flow\Mvc\ActionRequest|null $originalRequest
     * @return string|void
     */
    public function onAuthenticationSuccess(\TYPO3\Flow\Mvc\ActionRequest $originalRequest = null)
    {
        // TODO: Implement onAuthenticationSuccess() method.
    }

}